### ISSUE TITLE
Firefox-9999 depends on rust 1.21.0 and cargo 0.22.0

### ISSUE THREAD

**Issue by okias** [pkulev/riru#39]
$SUBJ

**Comment by pkulev** [comment]
@vaartis, could you please do smthn

**Comment by vaartis** [comment]
rust and cargo aren't versioned in the ebuild, so it uses the latest. They aren't versioned because the version we need is in the rust overlay, iirc they don't really maintain beta/nightly rust build, so your only choise is to use -bin live ebuilds. Correct me if I'm wrong, but that seems to be the current state of rust in gentoo

**Comment by pkulev** [comment]
@okias, @vaartis, is there something we can do, or I can just close this issue?

**Comment by vaartis** [comment]
I'd say close it.

**Comment by pkulev** [comment]
Ok, closing it for now.
